-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE check_account_cheack_account_id_seq;

CREATE SEQUENCE check_account_cheack_account_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE s_category_s_type_seq;

CREATE SEQUENCE s_category_s_type_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE subj_s_id_seq;

CREATE SEQUENCE subj_s_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE subj_s_type_seq;

CREATE SEQUENCE subj_s_type_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public.category_type definition

-- Drop table

-- DROP TABLE category_type;

CREATE TABLE category_type (
	s_type int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Внешний ключ из s_type в таблице статей бюджета)
	category_name varchar(32) COLLATE "ru-RU-x-icu" NOT NULL, -- Название категории
	category_code varchar(32) COLLATE "en-US-x-icu" NOT NULL, -- Системный код категории
	budget_limit float8 NULL, -- Лимит по категории (например, на месяц)
	is_active bool NOT NULL, -- Активна ли категория
	category_desc text COLLATE "ru-RU-x-icu" NULL, -- Пояснение к категории
	created_at _timestamp NOT NULL, -- Дата создания категории
	created_by varchar(64) COLLATE "en-US-x-icu" NOT NULL, -- Идентификатор пользователя, создавшего категорию
	CONSTRAINT s_type_uni UNIQUE (s_type)
);
COMMENT ON TABLE public.category_type IS 'Категории операций';

-- Column comments

COMMENT ON COLUMN public.category_type.s_type IS 'Внешний ключ из s_type в таблице статей бюджета)';
COMMENT ON COLUMN public.category_type.category_name IS 'Название категории';
COMMENT ON COLUMN public.category_type.category_code IS 'Системный код категории';
COMMENT ON COLUMN public.category_type.budget_limit IS 'Лимит по категории (например, на месяц)';
COMMENT ON COLUMN public.category_type.is_active IS 'Активна ли категория';
COMMENT ON COLUMN public.category_type.category_desc IS 'Пояснение к категории';
COMMENT ON COLUMN public.category_type.created_at IS 'Дата создания категории';
COMMENT ON COLUMN public.category_type.created_by IS 'Идентификатор пользователя, создавшего категорию';


-- public.check_account definition

-- Drop table

-- DROP TABLE check_account;

CREATE TABLE check_account (
	cheack_account_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	account_name varchar(32) COLLATE "ru-RU-x-icu" NOT NULL, -- Название счета для пользователя
	account_type_id int8 NOT NULL, -- Уникальный ID
	acc_currency varchar(3) NOT NULL, -- Валюта счета
	acc_balance float8 NOT NULL, -- Текущий баланс счета
	acc_initial_balance float8 NOT NULL, -- Начальный баланс счета
	acc_owner_name varchar(64) COLLATE "ru-RU-x-icu" NOT NULL, -- Имя владельца счета
	acc_owner_id varchar(64) NULL, -- ID владельца счета
	bank_name varchar(64) COLLATE "ru-RU-x-icu" NULL, -- Название банка
	acc_is_active bool NOT NULL, -- Активен ли счет
	acc_is_default bool NOT NULL, -- Счет по умолчанию для операций
	credit_limit float8 NULL, -- Кредитный лимит для кредитных карт
	CONSTRAINT acc_type_id_pk PRIMARY KEY (account_type_id),
	CONSTRAINT check_account_id_uni UNIQUE (cheack_account_id)
);
COMMENT ON TABLE public.check_account IS 'Типы счетов';

-- Column comments

COMMENT ON COLUMN public.check_account.account_name IS 'Название счета для пользователя';
COMMENT ON COLUMN public.check_account.account_type_id IS 'Уникальный ID';
COMMENT ON COLUMN public.check_account.acc_currency IS 'Валюта счета';
COMMENT ON COLUMN public.check_account.acc_balance IS 'Текущий баланс счета';
COMMENT ON COLUMN public.check_account.acc_initial_balance IS 'Начальный баланс счета';
COMMENT ON COLUMN public.check_account.acc_owner_name IS 'Имя владельца счета';
COMMENT ON COLUMN public.check_account.acc_owner_id IS 'ID владельца счета';
COMMENT ON COLUMN public.check_account.bank_name IS 'Название банка';
COMMENT ON COLUMN public.check_account.acc_is_active IS 'Активен ли счет';
COMMENT ON COLUMN public.check_account.acc_is_default IS 'Счет по умолчанию для операций';
COMMENT ON COLUMN public.check_account.credit_limit IS 'Кредитный лимит для кредитных карт';


-- public.periodicity definition

-- Drop table

-- DROP TABLE periodicity;

CREATE TABLE periodicity (
	periodicity_id int4 NOT NULL, -- Внешняя ссылка на справочник типов периодичности
	period_name varchar(32) COLLATE "ru-RU-x-icu" NULL, -- Название периода - "Ежемесячно"
	period_code varchar(16) NOT NULL, -- Системное название - monthly
	days_interval int4 NULL, -- Интервал в днях
	sort_order int4 NOT NULL -- Порядок в выпадающем списке
);
COMMENT ON TABLE public.periodicity IS 'Типы переодичности операций';

-- Column comments

COMMENT ON COLUMN public.periodicity.periodicity_id IS 'Внешняя ссылка на справочник типов периодичности';
COMMENT ON COLUMN public.periodicity.period_name IS 'Название периода - "Ежемесячно"';
COMMENT ON COLUMN public.periodicity.period_code IS 'Системное название - monthly';
COMMENT ON COLUMN public.periodicity.days_interval IS 'Интервал в днях';
COMMENT ON COLUMN public.periodicity.sort_order IS 'Порядок в выпадающем списке';


-- public.subj definition

-- Drop table

-- DROP TABLE subj;

CREATE TABLE subj (
	s_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Уникальный идентификатор статьи бюджета.
	s_name varchar(32) COLLATE "ru-RU-x-icu" NOT NULL, -- Наименование статьи бюджета.
	s_type int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Ссылка на справочник типов.
	amount float8 NOT NULL, -- Сумма
	currency varchar(3) NOT NULL, -- Валюта
	operation_date date NOT NULL, -- Дата проведения финансовой операции
	description varchar(32) COLLATE "ru-RU-x-icu" NULL, -- Подробное описание операции
	tags text COLLATE "ru-RU-x-icu" NULL, -- Массив тегов для категоризации
	created_at timestamp NOT NULL, -- Дата и время создания записи
	created_by varchar(64) NOT NULL, -- Идентификатор пользователя, который создал запись
	updated_at timestamp NOT NULL, -- Дата и время последнего обновления записи
	updated_by varchar(64) NOT NULL, -- Идентификатор пользователя, обновившего запись
	check_account_id int8 NOT NULL, -- Идентификатор счета, к которому относится статья бюджета.
	periodicity_id int4 NULL, -- Ссылка на спрвочник типов переодичности
	CONSTRAINT subj_id_pk PRIMARY KEY (s_id),
	CONSTRAINT fk_subj_stype FOREIGN KEY (s_type) REFERENCES category_type(s_type) ON DELETE RESTRICT ON UPDATE RESTRICT
);
COMMENT ON TABLE public.subj IS 'Статья бюджета';

-- Column comments

COMMENT ON COLUMN public.subj.s_id IS 'Уникальный идентификатор статьи бюджета.';
COMMENT ON COLUMN public.subj.s_name IS 'Наименование статьи бюджета.';
COMMENT ON COLUMN public.subj.s_type IS 'Ссылка на справочник типов.';
COMMENT ON COLUMN public.subj.amount IS 'Сумма';
COMMENT ON COLUMN public.subj.currency IS 'Валюта';
COMMENT ON COLUMN public.subj.operation_date IS 'Дата проведения финансовой операции';
COMMENT ON COLUMN public.subj.description IS 'Подробное описание операции';
COMMENT ON COLUMN public.subj.tags IS 'Массив тегов для категоризации';
COMMENT ON COLUMN public.subj.created_at IS 'Дата и время создания записи';
COMMENT ON COLUMN public.subj.created_by IS 'Идентификатор пользователя, который создал запись';
COMMENT ON COLUMN public.subj.updated_at IS 'Дата и время последнего обновления записи';
COMMENT ON COLUMN public.subj.updated_by IS 'Идентификатор пользователя, обновившего запись';
COMMENT ON COLUMN public.subj.check_account_id IS 'Идентификатор счета, к которому относится статья бюджета.';
COMMENT ON COLUMN public.subj.periodicity_id IS 'Ссылка на спрвочник типов переодичности';
