server.port=8080
server.host=0.0.0.0
server.backlog=50
jetty.idleTimeout=30000

log.level=INFO
log.level.budget=DEBUG
log.level.io.javalin=INFO
log.showDateTime=true
log.dateTimeFormat=yyyy-MM-dd HH:mm:ss
